using System;
using System.CodeDom;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Reflection;
using System.IO;
using Microsoft.CSharp;

namespace _146
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("QUESTION 146 \nYou are developing an application that generates code.The application includes the following code segment.");
            Console.WriteLine("\npublic string GenerateCode(string className, string methodName)\n{\n\t...\n\tvar ct = new CodeTypeDeclaration(className);\n\t...\n}");
            Console.WriteLine("\nYou need to ensure that code generated by the GenerateCode() method represents a class that can beaccessed by all objects in its application domain.\nWhich two code segments can you insert at line 05 to achieve the goal? Each correct answer presents acomplete solution.\nNOTE: Each correct selection is worth one point.");
            Console.WriteLine("\nA. ct.Attributes = MemberAttributes.Public;\nB. ct.IsStruct = true;\n   ct.Attributes = MemberAttributes.Public;\nC. ct.IsClass = true;\n   ct.Attributes = MemberAttributes.Public;\nD. ct.IsClass = true;\n   ct.Attributes = MemberAttributes.Private;");
            Console.WriteLine("\n\nCorrect Answer: AC.");
            Console.WriteLine("\n\n Incorrecta. Es la A y la C, pero en la C sobra la segunda sentencia");

            Console.WriteLine("\n\nPara probar se pone el código del ejemplo y desde el Main se crea una instancia de la clase GenerateCode\n pasándole como nombre de clase: miClase y como nombre de metodo: miMetodo. ");
            // Console.WriteLine("\n\nstring seCreo = GenerateCode('miClase', 'miMetodo');\n");
            //Console.WriteLine("\nmiClase mc = new miClase()\nmc.miMetodo()");

            string gc = new CodeDomGeneration().GenerateCode("miClase", "miMetodo");
            Console.WriteLine(gc);
        }
    }
    

    public class CodeDomGeneration
    {
        public string GenerateCode(string className, string methodName)
        {
            CodeDomProvider provider = CodeDomProvider.CreateProvider("CSharp");
            CodeCompileUnit cu = new CodeCompileUnit();
            CodeNamespace ns = new CodeNamespace("_146");
            ns.Imports.Add(new CodeNamespaceImport("System"));
            cu.Namespaces.Add(ns);

            var ct = new CodeTypeDeclaration(className)           // Create Class className
            {
                //ct.Attributes = MemberAttributes.Public;        // NO aplica a la clase  
                //Attributes = MemberAttributes.Private,          // No aplica a la clase  
                //TypeAttributes = TypeAttributes.NestedPrivate,  // Aplica para generar una clase privada
                TypeAttributes = TypeAttributes.Public,
                IsClass = true,
                //IsInterface = true,
                //IsStruct = true,
                //IsPartial = true,
            };

            ns.Types.Add(ct);

            /*var ct1 = new CodeTypeDeclaration("subClass");
            //ct1.Attributes = MemberAttributes.Private; // No aplica a la subclase
            ct1.TypeAttributes = TypeAttributes.NestedPrivate;
            ct1.IsClass = true;
            ct.Members.Add(ct1);*/

            var mt = new CodeMemberMethod { Name = methodName }; // Create Method
            var csSystemConsoleType = new CodeTypeReferenceExpression("System.Console");
            var cs1 = new CodeMethodInvokeExpression(csSystemConsoleType, "WriteLine", new CodePrimitiveExpression("Customer Added"));
            mt.Attributes = MemberAttributes.Private;
            mt.Statements.Add(cs1);
            ct.Members.Add(mt);

            String sourceFile;
            if (provider.FileExtension[0] == '.')
                sourceFile = "TestGraph" + provider.FileExtension;
            else
                sourceFile = "TestGraph." + provider.FileExtension;
            // Create an IndentedTextWriter, constructed with a StreamWriter to the source file.
            IndentedTextWriter tw = new IndentedTextWriter(new StreamWriter(sourceFile, false), "    ");
            provider.GenerateCodeFromCompileUnit(cu, tw, new CodeGeneratorOptions());  // Generate source code using the code generator.
            tw.Close();

            string gc = File.ReadAllText(sourceFile);
            return gc;
        }
    }


}



